---
title: "CaseStudy11Afelie"
author: "Adrian Elie"
date: "11/15/2022"
output: html_document
---

```{r}
library(tidyverse)
library(spData)
library(sf)
library(mapview) # new package that makes easy leaflet maps
library(foreach)
library(doParallel)
library(tidycensus)
```

census data refinement
```{r}
census_api_key("Your API Key Here", install = TRUE)
racevars <- c(White = "P005003", 
              Black = "P005004", 
              Asian = "P005006", 
              Hispanic = "P004003")

options(tigris_use_cache = TRUE)
erie <- get_decennial(geography = "block", variables = racevars, 
                      state = "NY", county = "Erie County", geometry = TRUE,
                      summary_var = "P001001", cache_table=T)

eriecrop <- st_crop(erie, c(xmin=-78.9,xmax=-78.85,ymin=42.888,ymax=42.92))
```

Foreach

```{r}
erieforeach <- foreach(i = unique(eriecrop$variable), .combine=rbind) %do%
  filter(eriecrop, variable == i) %>%
    st_sample(size=.$value) %>%
    st_as_sf() %>%
    mutate(variable = i)


mapview(erieforeach, zcol = 'variable', alpha = 0, cex = 0.1)
```

mapview
```{r}
mapview(buf_block, zcol = "variable", cex = 0.1, alpha = 0)
```
